import type { SubtitleEntry, SubtitleStyle } from '@/types';
import { toSRTTime, toASSTime } from './utils';

/**
 * Generate SRT subtitle content from entries
 */
export function generateSRT(entries: SubtitleEntry[]): string {
  return entries
    .map(
      (e) =>
        `${e.index}\n${toSRTTime(e.start)} --> ${toSRTTime(e.end)}\n${e.text.trim()}\n`
    )
    .join('\n');
}

/**
 * Generate ASS subtitle content from entries + optional style
 */
export function generateASS(
  entries: SubtitleEntry[],
  title = 'OshiSub',
  style?: SubtitleStyle
): string {
  const hexToASS = (hex: string) => {
    const r = parseInt(hex.slice(1, 3), 16);
    const g = parseInt(hex.slice(3, 5), 16);
    const b = parseInt(hex.slice(5, 7), 16);
    return `&H00${b.toString(16).padStart(2, '0').toUpperCase()}${g.toString(16).padStart(2, '0').toUpperCase()}${r.toString(16).padStart(2, '0').toUpperCase()}`;
  };

  const fontFamily = style?.fontFamily ?? 'Arial';
  const fontSize = style?.fontSize ?? 52;
  const primaryColor = style ? hexToASS(style.color) : '&H00FFFFFF';
  const outlineColor = style ? hexToASS(style.outlineColor) : '&H00000000';
  const bold = style?.bold ? -1 : 0;
  const italic = style?.italic ? -1 : 0;
  const alignment = style?.position === 'top' ? 8 : 2;
  const marginV = style?.marginV ?? 50;

  const header = `[Script Info]
; Generated by OshiSub
Title: ${title}
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
PlayResX: 1920
PlayResY: 1080
YCbCr Matrix: TV.709

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,${fontFamily},${fontSize},${primaryColor},&H000000FF,${outlineColor},&H80000000,${bold},${italic},0,0,100,100,0,0,1,2.5,1.5,${alignment},10,10,${marginV},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;

  const dialogues = entries
    .map(
      (e) =>
        `Dialogue: 0,${toASSTime(e.start)},${toASSTime(e.end)},Default,,0,0,0,,${e.text.trim()}`
    )
    .join('\n');

  return header + dialogues + '\n';
}

/**
 * Download a text file to the user's machine
 */
export function downloadFile(content: string, filename: string, mimeType = 'text/plain'): void {
  const blob = new Blob([content], { type: `${mimeType};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
